spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    #邮箱配置
  mail:
    host: smtp.163.com
    #邮箱
    username: 17605058037@163.com
    #这里不是填登录密码，填邮箱的授权码
    password: VSWVDGFWYLERLTEH
    port: 465
    required: true
    properties:
      #邮箱地址：
      from: xxxx@163.com
      #必须配置，不然有可能不会报错
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      required: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true

file:
  path:/x
server:
  port: 2223

alipay:
  appId: 9021000122694378
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcodQqMzI/Q1/Xah1OS7USR/FOklEbl3mt4LgcPLFGFqoNbsBzO4/TeKvoMP/GA4CVCj3EiSDo4dWAXaTSAXjXWrHllE7cchYUkPlVJFNBWvwUmwhquLXOpT3WfECHbUo3dhPX/UDWgX7AKeFd9U3CFCLvw/ZLoZG8JlU8o+vMXdZLeG143mEi2mFJWwcfSf9TAezS/bLmTFZqu2ntQQ9+MvaBAbpTAEdM+SGS6QDP1tzM7IC+Io9hAxgG796d5WmLzXeI0pF5dkf3FYV7PnUDqvAcXIHwb26r3CNkMLRhXvh7EEpHX9kKjh4UrAPcncbsuHz2sx5D8oFHDU5LWkwDAgMBAAECggEAH2n1e2E5OqbwmeuWZRWaA0iahP+jdL00kkL3qfIiO8Rf5sHHp1TSy77v+2mYYsZhC4M6UCiQiSSCBXTCkbvp2IdAFqNgDaZz9zv8Ra87Y2g0Fo3hakYRcJiDhnj1GDQ7JlRwNml8j4j5OuEragTAy6PuPdg3lYOaDvpBLiBSMnJtSdOcnPXT2rgUqB8fzbXD3YlDYggS2swd7bqUK8g5cmm+sADGe2AzD5YBXRgfIt98F/oSc0+OFnkYvSejXkR3zTZDljrB2PdDI5nUtNW/gT2fqKUSM+znvRE0DYv/xp9TlGnD9m1UP2FFO0Rt0PIValDqWot9jYZC2fI9aGM1QQKBgQD4pq0w2ssEDLODlBJxBsBjVR4yPD8J5wtCAVuwPQK62ZXgnoEyXa9D8Skssg8pAX0KhneA/xaNRiD8UlbqsDp40FwMz5NjpJ0SLM1VDIyhQIvheU5J+OJKPjWKRpM1Oyg/2ldW3K6068OQmWkhTjvh0HdlJu2mQfgIKIsbAcEqlwKBgQChQu0UGFdIMm7dFLkVnLbDqN8xQPsFLqQpkPC/8++zA5jba8iLxdG+pkUb7Ul6aoB7p2h8mmRToiT3l0wgiBTGUYc3D+krRBO3NvE9ZA00YrqyRhlhtJG+zNV50ltUGA1jU1XYxOHbu0Z9WCvNunqzee4cG2HnFRGujw/YtZBzdQKBgEXA9Fr9NfCn44Ao/NdqTnRPP45WKlUL1LOqj98r7mUefxYpQRMxBubnc2aPeQNG4J4gRMwSQ3BUWRKPwsRJtc2InhoV7UIJvuqHWP7f61+dLOCO2DCWOl0bgIeO7uMC+nKXPOMoO3aToSQidUSbnt7lTWk593cpkHwxa3yjDF53AoGAVFo2uwE0fr5qwVg6rHRqIZSvEwuDgqVwF5IKbM4DvycNiRErOPnECi7dDYukmNUm2geqnyr/ecPiBGTu3EFyZH529TVsaUZV7cteixdP1Owj7ma+lh4m8qAgtnVzclyWfDM2P4pU/mRKrfw2BYoa7tDD3Y3xOzgJJL8OsfPfWJUCgYEA8DAnksOdYYIk25J/BKjOJzn4BWwCan/eo1B8BHavPhd7yOUj5d19Yr5BqXaTsPyR1AW9vdYWUksj00HKISDYwWr6Qwqf7zdAdHw8Le1HVLwhcmkVNgXgCdpFCWDU+PX9x2+9NhuyiALf305UHUlRPVFtecut7o3gc5exc5rgZFU=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlBu//vbUsNc09FYp/Ie5ZJ91SktjnmOaKuuKRtvDATnF10bB8dZ6EWG2EdfN6S+qR4ubL8xUX9EskfFwFHE4aytwbbEyB0DgpteCBK16na5OBSJH29Ey3qpXFPEofxCtGliVYf2YB/c4x0YSLeDm9C1E0jr20qmL+duO0mHOjK/x/sNjOQkM5/ypncKk5fSeiMX3+kEexyR1JsYKsEKO0ytLRboAfvzObI+uXJTEvnTQMC2HLdHTXCECiNJvfskhxUyFDwNg2jD833nWsKFTHyQkrmvWjJTGMHIcmUBZ/oWJeYw6HrAipI3aEFsQj2T31qihDGSxInzB/grMS2YkowIDAQAB
  notifyUrl: http://vhiwgb.natappfree.cc/alipay/notify
